[package]
name = "cw-ibc-transfer"
version.workspace = true
authors.workspace = true
edition = "2021"

[dependencies]
cosmwasm-std = { workspace = true }
cw2 = { workspace = true }
cw-storage-plus = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
neutron-sdk = { workspace = true }
